name: DeathParticle
main: lenlenlL6\deathparticle\DeathParticle
author: lenlenlL6, BeeAZZ
api: 4.0.0
version: 1.0.1

permissions:
 deathparticle.command.use:
  description: Permission to use the command DeathParticle
  default: op
